### ISSUE TITLE
readme has a bug

### ISSUE THREAD

**Issue by ghost** [Noxyntious/meower#2]
.

**Comment by Noxyntious** [comment]
what?

**Comment by korewaChino** [comment]
reporting this for sexual harassment

**Comment by lleyton** [comment]
on GitHub? at all? seriously?

**Comment by ghost** [comment]
oops sorry my cat hacked my pc i would never actually do this so sorry for that

**Comment by korewaChino** [comment]
sexual harassment is no joke. this is not funny.

**Comment by AtiusAmy** [comment]
making advances to someone and then spinning it as a joke tf is this 😭

**Comment by lleyton** [comment]
the edit too, wtf are you trying to hide, there's edit history on GH

**Comment by lleyton** [comment]
AHAHAHA, SHE DELETED HER ACCOUNT
