### ISSUE TITLE
Error handiling for when a non-integer is passed

### ISSUE THREAD

**Issue by ghost** [Noxyntious/meower#8]
you gotta add error handlilng for when someone passes a string instead of an integer

but nice project overall, looks really cool

![image](https://github.com/Noxyntious/meower/assets/103849459/71cbba06-7f47-455a-b279-07df8948409e)

**Comment by uncenter** [comment]
#7 should fix this :)

**Comment by uncenter** [comment]
Closed by #7 FYI.
